### ISSUE TITLE
Mission options...

### ISSUE THREAD

**Issue by jmcollin78** [robrich/gulp-rimraf#22]
Hello,

I try the very basic explains in README:
Delete a folder: use rimraf directly (you don't need gulp-rimraf!):
<code>
var rimraf = require('rimraf'); // rimraf directly
gulp.task('task', function (cb) {
  rimraf('./folder', cb);
});
</code>
But this leads to:
<code>
[12:18:35] AssertionError: rimraf: missing options
    at rimraf (d:\Projets\Clouderial\nodeProjects\cld-apps\node_modules\rimraf\rimraf.js:49:3)
    at Gulp.<anonymous> (d:\Projets\Clouderial\nodeProjects\cld-apps\gulpfile.js:307:5)
</code>
Do I miss something ?

JM.

**Comment by jmcollin78** [comment]
Hum... Looking at the rimraf code, and we have to pass a callback to make it works.
